__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение:__<br><br>
Правильно:<br>
Произведением матрицы $A = \left\|a_{ij}\right\|$ имеющей порядки m и n, и матрицы $B = \left\|b_{ij}\right\|$ включающей порядки n и k, называется матрица $C = \left\|c_{ij}\right\|$ c порядками m и k:
$$C = \begin{pmatrix}
c_{11} & c_{12} & \cdots & c_{1k}\\ 
c_{21} & c_{22} & \cdots & c_{2k}\\  
\cdots & \cdots & \ddots & \cdots \\ 
c_{m1} & c_{m2} & \cdots & c_{mk}\\ 
\end{pmatrix}.$$
наполненная элементами определяемыми формулой:<br>
$$c_{ij} = \sum_{p=1}^{n}a_{ip}\cdot b_{pj}$$
Матрицу A можно умножить не на любую матрицу B: __важно чтобы__
__число столбцов матрицы__ A __было равно числу строк матрицы__ B
<br>
__Проверим это условие на предложенных вариантах:__
<br>
а) A — матрица 4×2, B — матрица 4×2; - __AB - 2 не равно 4, перемножить__
__нельзя, BA - тоже нельзя перемножить, так как 2(стобла) не равно__
__колличеству строк 4.__<br>
<br>б) A — матрица 2×5, B — матрица 5×3; - __AB - перемножить можно,__
__размерность 2×3, ВА перемножать нельзя, так как 3 не равно 2.__
<br><br>в) A — матрица 8×3, B — матрица 3×8; - __AB - перемножить можно,__
__размерность 8×8, ВА перемножать можно, размерность 3×3.__
<br><br>A - квадратная матрица размером 4×4, В - квадратная матрица размером 4×4 - __АВ, ВА перемножить можно, размерность 4×4.__

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение:__<br><br>
Сумма:<br>
$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
+ \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
= 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$$


In [1]:
import numpy as np
import math

a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b

array([[ 5, -3],
       [ 3,  5]])


Произведение:<br>
$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
\cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
= 
\begin{pmatrix}
4 & -11\\ 
12 & 3
\end{pmatrix}
$$


In [2]:
a@b

array([[  4, -11],
       [ 12,  -3]])

найдем так как матрицы квадратные BA:<br>

$$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
\cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
= 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}
$$

In [3]:
b@a

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3\cdot A - 2 \cdot B + 4 \cdot C$ для матриц 
$$
A = \begin {pmatrix}
1 & 7\\
3 & -6
\end {pmatrix}, 
B = \begin {pmatrix}
0 & 5\\
2 & -1
\end {pmatrix}, 
C = \begin {pmatrix}
2 & -4\\
1 & 1
\end {pmatrix}.
$$

__Решение:__<br>
$$
3 \cdot
\begin {pmatrix}
1 & 7\\
3 & -6
\end {pmatrix}
- 2 \cdot
\begin {pmatrix}
0 & 5\\
2 & -1
\end {pmatrix}
+ 4 \cdot
\begin {pmatrix}
2 & -4\\
1 & 1
\end {pmatrix} = 
\begin {pmatrix}
3 & 21\\
9 & -18
\end {pmatrix}
+ 
\begin {pmatrix}
0 & -10\\
-4 & 2
\end {pmatrix}
+ 
\begin {pmatrix}
8 & -16\\
4 & 4
\end {pmatrix} 
=
\begin {pmatrix}
11 & -5\\
9 & -12
\end {pmatrix}$$

In [4]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a + (-2) * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $
A = \begin {pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end {pmatrix}$. 
Вычислить $A \cdot A^T$ и $A^T \cdot A$


__Решение__<br>
$A^T = \begin {pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end {pmatrix}$<br>
$A \cdot A^T = 
\begin {pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end {pmatrix}
\cdot
\begin {pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end {pmatrix}
=
\begin {pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end {pmatrix}$<br>

$A^T \cdot A = 
\begin {pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end {pmatrix}
\cdot
\begin {pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end {pmatrix}
=
\begin {pmatrix}
45 & 0\\
0 & 14
\end {pmatrix}$<br>

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

__5.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [8]:
"""Класс для операций сложения и умножения матриц"""
class Matrix:
    def __init__(self, matrix):
        self.matrix= matrix
        
    def __str__(self):
        return ','.join(map(str, self.matrix)).replace(']', '\n').replace('[', '').replace(',', '')
    
    def __add__(self, other):
        if len(self.matrix) == len(other.matrix):
            for row1, row2 in zip(self.matrix, other.matrix):
                if len(row1) != len(row2):
                    return f'Количество столбцов не равно, эти матрицы нельзя сложить'
            result = [[a + b for a, b in zip(row1, row2)] for row1, row2 in zip(self.matrix, other.matrix)]
        else:
            return f'Количество строк не равно, эти матрицы нельзя сложить'

    def __mul__(self, other):
        result = []
        try:
            for row in self.matrix:
                row_result = []
                for i in range(len(other.matrix[0])):
                    num = 0
                    for idx, el in enumerate(row):
                        num += (el * other.matrix[idx][i])
                    row_result.append(num)
                result.append(row_result)
            return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
        except:
            return f'Умножение матриц данной размерности невозможно'
        
m_1 = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_2 = Matrix([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(m_1)
print(m_2)
print(m_1 + m_2)

m_3 = Matrix([[4, 1], [5, -2], [2, 3]])
m_4 = Matrix([[ 4, 5, 2], [ 1, -2, 3]])

print(m_1 * m_2)
print(m_3 * m_4)
print(m_4 * m_3)

1 2 3
4 5 6
7 8 9

10 20 30
40 50 60
70 80 90

None
300 360 420
660 810 960
1020 1260 1500

17 18 11
18 29 4
11 4 13

45 0
0 14



In [9]:
#проверка работы класса
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a @ b

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [10]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [11]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

__6.__ Вычислить определитель<br>
<br>a)
$$\begin {vmatrix}
{sin(x)} & {-cos(x)}\\
{cos(x)} & {sin(x)}
\end {vmatrix}$$
<br>б)
$$\begin {vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end {vmatrix}$$
<br>в) 
$$\begin {vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end {vmatrix}$$

__Решение__<br>
<br>а) 
$$\begin {vmatrix}
{sin(x)} & {-cos(x)}\\
{cos(x)} & {sin(x)}
\end {vmatrix}
= {sin}^2 x + {cos}^2 x = 1$$
б)
$$\begin {vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end {vmatrix}
= 4 \cdot (5 \cdot 9 - 1 \cdot 0) - 
2 \cdot (0 \cdot 9 - 1 \cdot 0) +
3 \cdot (0 \cdot 0 - 5 \cdot 0) = 180
$$

In [12]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)

180.0

в)
$$\begin {vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end {vmatrix}
= 1 \cdot (5 \cdot 9 - 6 \cdot 8) - 
2 \cdot (4 \cdot 9 - 7 \cdot 6) +
3 \cdot (4 \cdot 8 - 5 \cdot 7) = 0
$$

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(c), 2)

-0.0

__7.__ Определитель матрицы А равен 4. Найдите:<br>
a) det($A^2$);<br>
б) det($A^T$);<br>
в) det($2 \cdot A$).

__Решение__<br>
a) det($A^2$);<br>
Воспользуемся правилом для двух квадратных матриц одинакогого размера:
$$ det(A \cdot B) = det A \cdot det B.$$
$det(A^2) = 4 \cdot 4 = 16;$<br> 
б) det($A^T$);<br>
Воспользуемся правилом - определитель транспортированной матрицы равен определителю исходной:
$$det A^T = det A $$
$$det A^T = 4$$
в) det($2 \cdot A$)<br>
Воспользуемся правилом - умножение строки  или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. <br>
Таким образом, если каждая строка увеличится в 2 раза, определитель всей матрицы увеличится в $2^n$ раз, где n - число строк (столбцов).
$$det(2 \cdot A) = 2^n \cdot 4 = 2^{n+2}$$

__8.__ Докажите что матрица
$$\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix}$$
вырожденная.

__Решение__<br>
Матрица является вырожденной, если ее определитель равен нулю.<br>
Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.<br>
__Так как вторая строка матрицы равна первой строке, умноженной на -2 то эти две строки линейно зависимы соответственно определитель матрицы равен нулю, что и означает, что матрица вырожденная__<br>
$\begin{vmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
    \end{vmatrix} = -2 \cdot (-14 \cdot 13 - 6 \cdot 7) - 7(4 \cdot 13 + 6 \cdot 3) - 3(4 \cdot 7 - 14 \cdot 3) = 448 - 490 + 42 = 0$

In [14]:
c = np.array([[-2, 7, -3], [4, -14, 6],[-3, 7, 13]])
np.linalg.det(c)

0.0

__4.__ Найдите ранг матрицы:<br>
<br>а) $\begin {pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix}$<br>
<br>б) $\begin {pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}$

__Решение__<br>
<br>а) $\begin {pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix}$<br>
Отнимем из второй строки первую:<br>
$\begin {pmatrix}
1 & 2 & 3\\
0 & -1 & -2\\
2 & 3 & 4
\end{pmatrix}$<br>
Отнимем из третьей строки первую, уммноженную на 2:<br>
$\begin {pmatrix}
1 & 2 & 3\\
0 & -1 & -2\\
0 & -1 & -2
\end{pmatrix}$<br>
Так как вторая и третья строка равны, удалим третью строку:<br>
$\begin {pmatrix}
1 & 2 & 3\\
0 & -1 & -2
\end{pmatrix}$<br>
Получилась верхне-треугольная матрица, таким образом, ранг матрицы равен 2.

In [15]:
a = np.array([[1, 2, 3], [1, 1, 1],[2, 3, 4]])
np.linalg.matrix_rank(a)

2

<br>б) $\begin {pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}$<br>
Переместим последную строку наверх на место первой<br>
$\begin {pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3
\end{pmatrix}$<br>
Из четвертой строки отнимем вторую умноженную на 2<br>
$\begin {pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 0 & 1
\end{pmatrix}$<br>
Получилась верхне треугольная матрица.<br>
Определитель матрицы треугольного вида равен произведению элементов, стоящих на её главной диагонали:<br>
В нашем случае произведение и определитель равны нулю так как во второй строке стоит ноль на главной диагонали.<br>
Если убрать вторую строку то ранг матрицы получается равен 3.

In [16]:
#проверка
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3