__1.__ Найти собственные векторы 
и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [1]:
import numpy as np
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__Решение__<br>
$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} \cdot 
\begin {pmatrix}
x \\
y
\end{pmatrix} = \lambda
\cdot \begin {pmatrix}
x \\
y
\end{pmatrix}$$
Оператор имеет единственное собственное значение, равное $\lambda_1 = \lambda_2 = -1$ Запишим систему для нахождения собмтвенных векторов:
$$\begin{cases}
-x = -x,\\
-y = -y 
\end{cases}$$
Система верна при любых значениях x и y, это означает, что любой вектор является для данного оператора собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__Решение__<br>
Найдем собственные значения матрицы:
$$\begin{vmatrix}
1 - \lambda & 1\\
-1 & 3 - \lambda
\end{vmatrix} = 
(1 - \lambda) \cdot (3 - \lambda) + 1 =0$$
$$\lambda_1 = \lambda_2 = 2$$
Подставим в систему наш вектор и проверим, подойдут ли заданные значения:
$$\begin{pmatrix}
1 & 1\\
-1 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
1\\
1
\end{pmatrix} = 2 \cdot
\begin{pmatrix}
1\\
1
\end{pmatrix}$$
$$\begin{cases}
2 = 2,\\
2 = 2
\end{cases}$$
Система верна при заданных значениях, значит, вектор является собственным

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [2]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
v, _ = np.linalg.eig(A)
print(v)


[ 3. -3.  3.]


In [3]:
vect = np.array([3, -3, -4])
print(f'A * vect = {A.dot(vect)}')
print(f'lambda1 * vect = {v[0] * vect}')
print(f'lambda2 * vect = {v[1] * vect}')
print(f'lambda3 * vect = {v[2] * vect}')

A * vect = [ -9   9 -12]
lambda1 * vect = [  9.  -9. -12.]
lambda2 * vect = [-9.  9. 12.]
lambda3 * vect = [  9.  -9. -12.]


Вектор не является собственным

In [4]:
b = np.array([[1, 1], [-1, 3]])
v, w = np.linalg.eig(A)
w

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])