__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__Решение__<br>
Из трьетего уравнения вычтем первое и из второго первое:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2\cdot x_{4}=0 \\
x_{1}+3\cdot x_{4}=-2 \\
-2\cdot x_{1}+3\cdot x_{4} = 4
\end{cases}$$
из второго выразим $x_1=−2−3\cdot x_4$, из третьего выразим $x_3=2−1.5\cdot x_4$ подставим в первое, найдем $x_2$:
$$−2−3\cdot x_4+x_2−2+1.5\cdot x_4 −2\cdot x_4=0$$
$$x_2=4 −3.5\cdot x_4$$
Общее решение выглядит так:
$$\begin{cases}
x_1=-2-3\cdot x_4\\
x_2=4-3.5\cdot x_4\\
x_3=2-1.5\cdot x_4
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение__

In [1]:
# a)
import numpy as np
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

rank A = 3
rank A_extended = 3


число неизвестных система совместна и имеет единственное решение

In [2]:
# б)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

rank A = 1
rank A_extended = 2


Система не совместна и не имеет решений

In [3]:
# в)
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

rank A = 2
rank A_extended = 2


ранги матриц равны 2, но число неизвестных 3, система имеет бесконечное количество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [4]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0,2]])
b = np.array([[3], [2], [4], [1]])
A_ext = np.hstack((A, b))
print(f'Система совместна: {np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext)}')
print(f'Имеет единственное решение: {np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == 4}')


Система совместна: True
Имеет единственное решение: True


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__<br>
Система будет несовместной когда $rankA < rank\tilde{A}$. $rankA = 2$. т.к. третья строка является линейной комбинацией первых двух $A_3=2\cdot A_2-A_1$ преобразуем матрицу. Из третье строки вычтем удвоенную вторую и затем сложим с первой

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[2] = A[2] - 2*A[1] + A[0]
A

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

Чтобы система была несовместной нужно чтобы после преобразований в расширенной матрице в третьей строке свободных членов был не 0, тоесть $c-2\cdot b+a\not= 0$

__5.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [6]:
def kramer(A, b):
    assert A.shape[0] == A.shape[1], 'Wrong matrix size!'
    det_A = np.linalg.det(A)
    result = []
    if np.abs(det_A) > 0.000001: #может быть ошибка округления
        for i in range(A.shape[0]):
            A_i = np.hstack((A[:, :i], b, A[:, i+1:]))
            result.append(np.linalg.det(A_i) / det_A)
        return np.round(result, 2)
    else:
        return 'det A is 0'
# a)
A = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]]).T
print(f'a) {kramer(A, b)}')
# б)
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]]).T
print(f'б) {kramer(A, b)}')


a) [5. 2.]
б) [ 2. -1.  1.]


__6*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [7]:
def LU(A):
    assert A.shape[0] == A.shape[1] and A[0][0] !=0 and np.abs(np.linalg.det(A)) > 0.00001, 'Невозможно разложить матрицу'
    L = np.zeros_like(A)
    U = np.zeros_like(A)
    # первая строка U и первый столбец L
    U[0] = A[0]
    L[:, 0] = A[:, 0] / U[0, 0]
    for i in range(A.shape[1]):
        for j in range(i, A.shape[1]):
            U[0, i] = A[0, i]
            L[i, 0] = A[i, 0] / U[0, 0]
            u_sum, l_sum = 0, 0
            for k in range(i):
                u_sum += L[i, k] * U[k, j]
                l_sum += L[j, k] * U[k, i]
            U[i, j] = A[i, j] - u_sum
            L[j, i] = (A[j, i] - l_sum) / U[i, i]
    return U, L
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U, L = LU(A)
print("a) ")
print("Матрица U:")
print(U)
print("Матрица L:")
print(L)
print("Матрица LU == A:")
print(L.dot(U))
print(A)
# б)
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53,
33]])
U, L = LU(A)
print("б) ")
print("Матрица U:")
print(U)
print("Матрица L:")
print(L)
print("Матрица LU == A:")
print(L.dot(U))
print(A)



a) 
Матрица U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]
Матрица L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]
Матрица LU == A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
б) 
Матрица U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]
Матрица L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]
Матрица LU == A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


__7*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [8]:
def LU_slau(A, b):
    U, L = LU(A)
    y = np.zeros(A.shape[0])
    x = np.zeros(A.shape[0])
    for i in range(A.shape[0]):
        y[i] = b[i] - (L[i, :i] * y[:i]).sum()
    for i in range(A.shape[0]-1, -1, -1):
        x[i] = (y[i] - (U[i, i+1:]*x[i+1:]).sum())/U[i, i]
    return x
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, 5])
x = LU_slau(A, b)
print(f'x = {x}')
print('Проверка')
for i in range(len(A)):
    print((x * A[0]).sum() == b[0])


x = [-4.41666667  4.08333333  1.91666667]
Проверка
True
True
True


__8*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [9]:
#Метод Гаусса
def gauss(A):
    n = len(A)
    for i in range(n):
        for j in range(i, n):
            if A[j][i] != 0:
                if i != j:
                    A[i], A[j] = A[j], A[i]
                break
        for j in range(i + 1, n):
            if A[j][i] != 0:
                l = -A[j][i] / A[i][i]
                for k in range(len(A[j])):
                    A[j][k] += l * A[i][k]
    result = []
    for i in range(n - 1, -1, -1):
        if A[i][i] == 0:
            return None
        for j in range(len(result)):
            A[i][len(A[i]) - 2 - j] *= result[j]
        x = A[i][len(A[i]) - 1]
        for j in range(len(A[i]) - 1):
            if j != i:
                x -= A[i][j]
        result.append(x / A[i][i])
    return [result[i] for i in range(len(result) - 1, -1, -1)]


print(gauss([
    [1, 2, 4, -5],
    [-2, 1, -3, 10],
    [3, -2, -5, 3]
]))

print(gauss([
    [1, 1, 1, 6],
    [1, -1, 2, 5],
    [2, -1, -1, -3]
]))

print(gauss([
    [0, 1, 1, 6],
    [1, 0, 2, 5],
    [2, -1, -1, -3]
]))

print(gauss([
    [0, 2, 5],
    [-1, -1, -3]
]))

print(gauss([
    [2, 4, -1, 2, 4],
    [7, -6, -1, 2, 9],
    [9, 1, -4, 0, 11],
    [2, 3, -4, 8, 9]
]))


[-1.0, 2.0, -2.0]
[1.0, 2.0, 3.0]
[1.5, 4.25, 1.75]
[0.5, 2.5]
[1.08, 0.040000000000000036, -0.30999999999999983, 0.6849999999999999]
